services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: bigdataenergy
      POSTGRES_PASSWORD: bigdataenergy
      POSTGRES_DB: big_data_energy
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: