services:
  db:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      POSTGRES_USER: bigdataenergy
      POSTGRES_PASSWORD: bigdataenergy
      POSTGRES_DB: big_data_energy
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  sonarqube:
    image: sonarqube:latest
    container_name: sonarqube_container
    depends_on:
      - sonarqube-db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarqube-db:5432/sonarqube
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    profiles:
      - sonarqube

  sonarqube-db:
    image: postgres:15-alpine
    container_name: sonarqube_db_container
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarqube
      POSTGRES_DB: sonarqube
    volumes:
      - sonarqube_pgdata:/var/lib/postgresql/data
    profiles:
      - sonarqube

volumes:
  pgdata:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_pgdata: